### ISSUE TITLE
Titillium

### ISSUE THREAD

**Issue by shaundon** [ubuwaits/beautiful-web-type#12]
[Titillium](http://www.google.com/fonts/specimen/Titillium+Web) is quite a nice font. 

A good example of it in use is on [Karma Runner](http://karma-runner.github.io/0.10/index.html).

I'm not entirely sure what the procedure is for submitting new suggestions here - does this suffice, or should I submit a pull request?

Thanks. Great repo by the way!

**Comment by ubuwaits** [comment]
Thank you for the suggestion. I'm personally not a fan of the font, so I won't be making any examples using it. In the time since I first created this site, a handful of other similar sites have popped up, many of which have many more examples. My approach is to keep this a fairly personal project where I only use typefaces I am particularly fond of.

**Comment by shaundon** [comment]
No problem - there's certainly advantages of keeping it curated rather than just a list of all available webfonts.

**Comment by JoshToan** [comment]
Hi,

Why do i keep getting emails from people about beautiful web type, they are very frequent and kind of a pain if im honest

**Comment by vohof** [comment]
You probably **watched** the repository instead of just a **star**.

**Comment by dmajoraddnine** [comment]
+1

On Mon, Jul 13, 2015 at 10:17 AM, Josh Toan <notifications@github.com>
wrote:

> Hi,
>
> Why do i keep getting emails from people about beautiful web type, they
> are very frequent and kind of a pain if im honest
>
> Sent from my iPhone
>
> > On 13 Jul 2015, at 09:47, Shaun Donnelly <notifications@github.com>
> wrote:
> >
> > No problem - there's certainly advantages of keeping it curated rather
> than just a list of all available webfonts.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubuwaits/beautiful-web-type/issues/12#issuecomment-120883958>
> .
>



-- 
Best
Matt Yetter
http://www.matt-yetter.com

**Comment by Eagerbob** [comment]
Yeah,

me too.

I guess I put my e-mail address somewhere, sometime?

Andre
13m2 effectieve websites
Sint Pieterspoortsteeg 23b
1012 HM Amsterdam
mail: andre@13m2.nl | tel. 06 55 742 227

Op 13 jul. 2015, om 12:21 heeft Matt Yetter <notifications@github.com> het volgende geschreven:

**Comment by firemountain** [comment]
me too, trés annoying :)

**Comment by jameslaneconkling** [comment]
To stop watching this repo (i.e. to stop receiving emails about issue comments), go to the [repo's issue page](https://github.com/ubuwaits/beautiful-web-type/issues), click **Unwatch** and change to **Ignoring**.

<img width="381" alt="screenshot 2015-07-13 11 21 03" src="https://cloud.githubusercontent.com/assets/4389360/8657293/a0fe1094-2951-11e5-9f28-2eedf70bd2a9.png">
