### ISSUE TITLE
Alegreya + Source {Sans,Code} Pro

### ISSUE THREAD

**Issue by padde** [ubuwaits/beautiful-web-type#13]
One combination that works very well for me is
- [Alegreya](http://www.fontsquirrel.com/fonts/alegreya)
- [Source Sans Pro](http://www.fontsquirrel.com/fonts/source-sans-pro)
- ([Source Code Pro](http://www.fontsquirrel.com/fonts/source-code-pro))

Since all of these are not in the examples yet, I'd love to see them added!

**Comment by ubuwaits** [comment]
Apologies for my *extremely* slow reply. I've just launched a totally new version of the site, where I've now included [Alegreya](https://beautifulwebtype.com/alegreya/) as a sample. I've also included [Source Serif Pro](https://beautifulwebtype.com/source-serif-pro/) and will be taking a closer look at the family typefaces that you've mentioned soon.
