### ISSUE TITLE
No font name rollovers on "Home" panel?

### ISSUE THREAD

**Issue by iDGS** [ubuwaits/beautiful-web-type#15]
The main headline, "Beautiful Web Type" is set in Abril Fatface, but on http://hellohappy.org/beautiful-web-type/ I had to view the page's source code to find that out. (Fringe benefit: I also learned the hard way that you kerned W-eb, which for more easily is discoverable if you highlight the text by selecting it.) But, my point is, that first panel at the top of the page--shouldn't the fonts in _it_ be conveniently identified too? (Pretty please?)

**Comment by ubuwaits** [comment]
I've just launched a completely new version of the site and all the samples are clearly labeled, with links to both the Google Fonts version (when available) and the GitHub repos for each typeface.
