### ISSUE TITLE
Arvo?

### ISSUE THREAD

**Issue by danvctr** [ubuwaits/beautiful-web-type#16]
https://www.google.com/fonts/specimen/Arvo

**Comment by ubuwaits** [comment]
Thanks for the suggestion. Now that I've launched the new version of the site I'm actively looking for new typefaces to add. I'll add this to my queue of faces to take a closer look at. At first glance, though, I think I would favor [Zilla Slab](https://beautifulwebtype.com/zilla-slab/) if I wanted to use a slab serif.
