### ISSUE TITLE
Use text-rendering:optimizeLegibility instead of kern hack

### ISSUE THREAD

**Issue by behdad** [ubuwaits/beautiful-web-type#17]
Instead of this hack:

```
    <h1>Beautiful W<span class="kern">eb</span> Type</h1>
```

You should specify text-rendering:optimizeLegibility, which will enable kerning for Latin text in Chrome and Safari.  Or is there another reason for that?

**Comment by khakiout** [comment]
:+1:

**Comment by killercup** [comment]
Alternatively/additionally, have a look at https://github.com/kennethormandy/normalize-opentype.css

**Comment by joshica** [comment]
cek saljem novu verziju  

--  
Best,
Jovan Stojanovic
jovanstojanovic.com

**Comment by ubuwaits** [comment]
I've just released a completely new version of the site and I've removed all the kerning hacks.
