### ISSUE TITLE
Donation button is missing

### ISSUE THREAD

**Issue by Isk1n** [ubuwaits/beautiful-web-type#18]
Hello! I don't see the donation button and https://www.coinbase.com/assets/tips.js gives 404. Maybe it is country specific. You should probably check it.

**Comment by vohof** [comment]
wut?

**Comment by Isk1n** [comment]
![screen](https://cloud.githubusercontent.com/assets/5972067/8592361/6669d82c-2637-11e5-96c0-f2c464d33997.png)

**Comment by kothar** [comment]
Coinbase shut down their tip button service in February in favour of ChangeTip: https://blog.coinbase.com/2015/02/10/shutting-down-the-coinbase-tip-button/

**Comment by ubuwaits** [comment]
Thanks for reminding me about this. I'm now using the ChangeTip donate button instead.
