### ISSUE TITLE
Add Josefin Sans

### ISSUE THREAD

**Issue by codeOfRobin** [ubuwaits/beautiful-web-type#21]
Hey!

What're the contributing guidelines like for this project? I wanna add [Josefin Sans](https://fonts.google.com/specimen/Josefin+Sans) because it's a whimsical font with some great use cases.

**Comment by jhanschoo** [comment]
cf. #12 . Seems like @ubuwaits prefers strong editorial control.

**Comment by tarang9211** [comment]
why am i getting notifications for this repo? 🤔

**Comment by strugee** [comment]
Probably because you're watching it? It should tell you the reason why on the right-hand side of the page, under the "unsubscribe" button.

**Comment by basilgohar** [comment]
The action that sent an e-mail out was back in October, so that's 
probably why some of us were surprised.  The thought also crossed my 
mind.  You can unwatch to stop getting these e-mails as mentioned before.

**Comment by tarang9211** [comment]
I came across this sight when I was learning typography! Sorry, it slipped out of my mind.

**Comment by codeOfRobin** [comment]
Okay then. Looks like I've stirred a hornets nest here. Let's forget this ever happened 😄

**Comment by iemejia** [comment]
Wait you don't need to immediately close it, even if @ubuwaits is curating what gets in, maybe he would agree about this font, no?

**Comment by jhanschoo** [comment]
@codeOfRobin what iemejia said. There's probably merit in your suggestion, just didn't want to get your hopes up :P

**Comment by AlfredJKwack** [comment]
ROFL. This entire conversation has just made my day for some reason. Thanks for the laughs everyone.
