### ISSUE TITLE
Suggestion: Hack Font

### ISSUE THREAD

**Issue by MyNameIsCosmo** [ubuwaits/beautiful-web-type#27]
[Hack](https://sourcefoundry.org/hack/) is a font designed for source code. I've found it readable on small screens and has not given me eye strain.

The font is open-source ([Here on Github!](https://github.com/source-foundry/Hack))
It is released under an MIT license.

Here are some example images.
![Type Face](https://sourcefoundry.org/hack/assets/img/mockup/Aa-mockup-2.png)
![Source Code](https://sourcefoundry.org/hack/assets/img/mockup/srcmockup.png)

**Comment by jdhoek** [comment]
I second this suggestion. Hack is well-thought-through font for code and console which builds on the impressive lineage of Bitstream Vera Sans Mono (by way of DejaVu Sans Mono).
