### ISSUE TITLE
Display error for Source Sans Pro w600 in Smallcap headlines

### ISSUE THREAD

**Issue by kuzeko** [ubuwaits/beautiful-web-type#32]
There is a problem in the Source Sans Pro showcase for Smallcap headlines `@weight 600` (see screenshot).
The fallback fond (serif) gets rendered.

<img width="612" alt="screenshot 2018-12-06 at 14 26 54" src="https://user-images.githubusercontent.com/532563/49587015-125d8f00-f963-11e8-8e28-8d243f77d7cc.png">

I'm using

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:63.0) Gecko/20100101 Firefox/63.0
```

**Comment by ubuwaits** [comment]
Ah, thanks for that. It seems that Firefox is the only browser that cares about the case of the source file within a `@font-face` declaration.
