### ISSUE TITLE
Source code fractions bug

### ISSUE THREAD

**Issue by dy** [ubuwaits/beautiful-web-type#39]
At https://beautifulwebtype.com/source-code-pro/ in google chrome I see 
![image](https://user-images.githubusercontent.com/300067/107990101-ad217180-6fa1-11eb-8b07-1b23e0f5b54b.png)

**Comment by ubuwaits** [comment]
I've updated the font files to the latest release from Apr 4 of this year, and this problem is still present in Firefox and Chrome (but not Safari). The problem appears to be with the font and not this site, so closing this issue for now.
